create DATABASE; -- to create a database
drop database; -- to delete the database
show databases; -- to list down all the database present

-- Select a database--

CREATE DATABASE CLASSDB;
USE CLASSDB;
SHOW TABLES;

--- NEW CHAPTER --
CREATE DATABASE FBDB;
USE FBDB;

-- CREATE TABLES --
CREATE TABLE USERS(
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(50),
    USERNAME VARCHAR(50),
    ID INT PRIMARY KEY AUTO_INCREMENT
);

SHOW TABLES; -- SHOW THE TABLES--

-- DESCRIBE THE TABLE || DETAIL OF THE TABLES--
DESC USERS;

-- INSERTING DETAILS IN THE TABLE --
INSERT USERS (USERNAME,EMAIL,PASSWORD) 
VALUES('MD ALAM', 'MDALAM@GMAIL.COM', '1234');

INSERT USERS(USERNAME,EMAIL,PASSWORD)
VALUES('ROHIT', 'ROHIT@GMAIL.COM','1919')

INSERT USERS(USERNAME,EMAIL,PASSWORD)
VALUES('AEJUN', 'ARJUN@GMAIL.COM','1818')

INSERT USERS(USERNAME,EMAIL,PASSWORD)
VALUES('SIMRAN', 'SIMRAN@GMAIL.COM','1989')

SELECT ID,EMAIL,USERNAME FROM USERS; -- SELECT DATA FROM TABLE --

SELECT * FROM USERS; -- TO VIEW ALL THE TABLE --

--- TO INSERT MULTIPLE VALUE INTO TABLE ---
INSERT USERS (USERNAME,EMAIL,PASSWORD) VALUES
('LAXMI SHAH', 'LAXMISHAH@ICLOUD.COM','1836'),
('MOHIT KUMAR', 'MOHITKUMAR@ICLOUD.COM','1256'),
('RINKU DEVI', 'RINKU001@GMAIL.C.COM','1376');


-- CREATE A POST WITH ID, CONTENT, USER_ID, CREATE_ID COLUMNS
CREATE TABLE POST(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(255),
    USER_ID INT, -- TO WHO THIS POST IS BELONG TO
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT POST(CONTENT,USER_ID) 
VALUES ("THIS IS EARTH","20"),
("THIS IS MARCH","30"),
("THIS IS MOON","11");

SELECT * FROM POST;

-- WHERE COMMAND --
SELECT * FROM USERS WHERE ID>3;
SELECT * FROM USERS WHERE ID=5;

SELECT *FROM USERS WHERE PASSWORD=1234;
SELECT *FROM USERS WHERE USERNAME='MD ALAM';

SELECT *FROM POST WHERE CONTENT = 'THIS IS EARTH' AND ID =1;

-- Like operators --

-- %SAH% = START WIDTH SHAH END WITH SAH
SELECT * FROM USERS WHERE EMAIL LIKE '%SHAH%';

-- %SAH = START WIDTH SHAH END WITH SAH 
SELECT * FROM USERS WHERE EMAIL LIKE 'MD%';

-- SAH% = START WIDTH SAH END WITH ANYTHING
SELECT * FROM USERS WHERE EMAIL LIKE 'SAH%';

SELECT *FROM USERS WHERE EMAIL LIKE '%S%';

--SHORTING THE DATA --
SELECT*FROM USERS;

SELECT *FROM USERS ORDER BY ID ASC; 
SELECT *FROM USERS ORDER BY USERNAME ASC; 


-- DELETING FROM TABLE --
DELETE FROM USERS WHERE ID=1; -- DELETE ONLY COLUMN ID IS WHERE ID =1 -- 
DROP TABLE POST -- DELETE HOLE TABLE --

-- UPDATING IN THE TABLE --
SELECT *FROM POST;
UPDATE POST SET CONTENT ='YOUR WORLD' WHERE ID= 2;
UPDATE POST SET `CONTENT`='YOUR MOON' WHERE ID=3;


